[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "helm-torrent"
version = "0.8.0"
authors = [
  { name="Piratebird" },
]
description = "Torrent automation MVP"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.31.0",
    "python-dotenv>=1.0.0",
    "libtorrent>=2.0.0,<2.1.0"
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-cov",
    "responses"
]

[project.urls]
"Homepage" = "https://github.com/Piratebird/helm"

[project.scripts]
helm = "helm.cli:main"

[tool.setuptools.packages.find]
where = ["src"]

[tool.ruff]
line-length = 120
target-version = "py38"
select = ["E", "F", "W", "I", "B"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.10"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
